#!/usr/bin/env bash
# =====================================================================
# Ronin Rewards — Mainnet initialization (ONE-TIME)
# =====================================================================
#
# After the program is deployed to Mainnet (deploy-mainnet.sh complete),
# you MUST call initialize() ONCE to create the RewardConfig + RewardVault
# PDAs. This script does that.
#
# This script is IDEMPOTENT — if the PDAs already exist (e.g. you ran it
# twice by accident), the second call will fail with "already in use"
# and the script will exit 0 (treat it as success).
#
# PREREQUISITES:
#   - Program is deployed to Mainnet (run deploy-mainnet.sh first)
#   - Program keypair file is at programs/ronin_rewards/ronin_rewards-keypair.json
#   - Anchor IDL is at target/idl/ronin_rewards.json
#   - Admin wallet at ~/.config/solana/id.json
#   - Admin wallet has SOL balance >= 0.05 SOL (for rent + fees)
#
# USAGE:
#   bash scripts/initialize-mainnet.sh
# =====================================================================

set -euo pipefail

GREEN='\033[0;32m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
log()    { echo -e "${GREEN}[init]${NC} $1"; }
error()  { echo -e "${RED}[error]${NC}  $1"; }
step()   { echo -e "\n${BLUE}=== $1 ===${NC}"; }

PROGRAM_ID="FHd1Nvwfvywkvw6Xcdt2QrgiLWPo2qG1KLrUoCwHWKfU"
PROGRAM_KEYPAIR="programs/ronin_rewards/ronin_rewards-keypair.json"

step "Step 1: Verify Mainnet + admin wallet"
solana config set --url https://api.mainnet-beta.solana.com > /dev/null
DEPLOYER=$(solana address)
BALANCE=$(solana balance | awk '{print $1}')
log "Deployer: $DEPLOYER"
log "Balance:  $BALANCE SOL"

if (( $(echo "$BALANCE < 0.05" | bc -l) )); then
  error "Insufficient SOL — need at least 0.05 SOL for rent + fees."
  exit 1
fi

step "Step 2: Confirm this is the ONE-TIME Mainnet initialization"
echo "You are about to call initialize() on the Ronin Rewards program at:"
echo "  $PROGRAM_ID"
echo "  Cluster: Mainnet"
echo ""
echo "This creates the RewardConfig + RewardVault PDAs and costs ~0.04 SOL"
echo "(rent for two PDA accounts). This is a ONE-TIME cost."
echo ""
read -p "Type 'INITIALIZE' to confirm: " -r
echo
if [[ "$REPLY" != "INITIALIZE" ]]; then
  echo "Aborting."
  exit 1
fi

step "Step 3: Call initialize() via Anchor CLI"

# Use Anchor's TypeScript client to call initialize()
# This requires the IDL file (target/idl/ronin_rewards.json) generated
# by `anchor build` during deploy-mainnet.sh
if [[ ! -f "target/idl/ronin_rewards.json" ]]; then
  error "IDL file not found: target/idl/ronin_rewards.json"
  echo "Did you run deploy-mainnet.sh? The IDL is generated by 'anchor build'."
  exit 1
fi

node -e "
const anchor = require('@coral-xyz/anchor');
const web3 = require('@solana/web3.js');
const fs = require('fs');

(async () => {
  const idl = JSON.parse(fs.readFileSync('target/idl/ronin_rewards.json', 'utf8'));
  const PROGRAM_ID = new web3.PublicKey('$PROGRAM_ID');

  // Connect to Mainnet
  const connection = new web3.Connection('https://api.mainnet-beta.solana.com', 'confirmed');

  // Load the deployer wallet (default Solana CLI keypair)
  const walletPath = require('os').homedir() + '/.config/solana/id.json';
  const secret = JSON.parse(fs.readFileSync(walletPath, 'utf8'));
  const admin = web3.Keypair.fromSecretKey(new Uint8Array(secret));

  console.log('Admin pubkey:', admin.publicKey.toBase58());

  const provider = new anchor.AnchorProvider(connection, new anchor.Wallet(admin), { commitment: 'confirmed' });
  const program = new anchor.Program(idl, provider);

  // Derive PDAs
  const [rewardConfig] = web3.PublicKey.findProgramAddressSync([Buffer.from('reward_config')], PROGRAM_ID);
  const [rewardVault] = web3.PublicKey.findProgramAddressSync([Buffer.from('reward_vault')], PROGRAM_ID);

  console.log('Reward Config PDA:', rewardConfig.toBase58());
  console.log('Reward Vault PDA: ', rewardVault.toBase58());

  // Check if already initialized
  const configInfo = await connection.getAccountInfo(rewardConfig);
  if (configInfo) {
    console.log('');
    console.log('ℹ️  RewardConfig already exists — initialization was already completed.');
    console.log('   Skipping. The program is ready to use.');
    return;
  }

  // Call initialize()
  console.log('');
  console.log('Calling initialize()...');
  const sig = await program.methods
    .initialize()
    .accounts({
      admin: admin.publicKey,
      rewardConfig,
      rewardVault,
      systemProgram: web3.SystemProgram.programId,
    })
    .signers([admin])
    .rpc();

  console.log('✅ initialize() succeeded!');
  console.log('Transaction signature:', sig);
  console.log('Solscan: https://solscan.io/tx/' + sig);

  // Verify by reading the config
  const config = await program.account.rewardConfig.fetch(rewardConfig);
  console.log('');
  console.log('--- RewardConfig (Mainnet) ---');
  console.log('Admin:        ', config.admin.toBase58());
  console.log('Paused:       ', config.paused);
  console.log('Total claims: ', config.totalClaims.toString());
  console.log('Total claimed:', config.totalClaimed.toString(), 'lamports');
})();
" || {
  error "initialize() failed."
  echo "Most common reasons:"
  echo "  - The RewardConfig PDA already exists (idempotent — already initialized)"
  echo "  - Insufficient SOL for rent (~0.04 SOL needed)"
  echo "  - The IDL is stale — rebuild with: anchor build"
  exit 1
}

step "Step 4: Verify"
echo "✅ Program is initialized on Mainnet."
echo ""
echo "Next steps:"
echo "  1. Fund the reward vault:"
echo "     bash scripts/fund-vault-mainnet.sh 0.1"
echo "  2. Update website .env.local to point at Mainnet"
echo "  3. Restart the dev server"
